### ISSUE TITLE
Instructions to reproduce the installer?

### ISSUE THREAD

**Issue by pipboy96** [nuukedo29/mifs#3]
Just to be sure the installer is safe, can you create an instruction for reproducing the installer (where `ffmpeg` and `7z` versions you used can be downloaded, how to reproduce `mifs.exe`). I'm asking due to https://www.virustotal.com/gui/file/3f277b447e135b22a87386ef6808feeab16a5a9246b10e7bed28bdd06c0339e6/detection.

**Comment by nuukedo29** [comment]
Will add instructions once i get some free time, the hits on VT are false positives from either UPX in pyinstaller or innosetup.

**Comment by flumf** [comment]
It's been over a month, can you please create a script or something in order to create reproducible builds?

It is important for the safety of everybody who uses this tool to make sure that it is 100% virus free.

Thank you :)

**Comment by nuukedo29** [comment]
> 
> 
> It's been over a month, can you please create a script or something in order to create reproducible builds?
> 
> It is important for the safety of everybody who uses this tool to make sure that it is 100% virus free.
> 
> Thank you :)

![Red_7a3b0a_6227359](https://user-images.githubusercontent.com/55753080/83297084-7623e980-a1e1-11ea-9080-7f23255adc23.jpg)

**Comment by flumf** [comment]
> > It's been over a month, can you please create a script or something in order to create reproducible builds?
> > It is important for the safety of everybody who uses this tool to make sure that it is 100% virus free.
> > Thank you :)
> 
> ![Red_7a3b0a_6227359](https://user-images.githubusercontent.com/55753080/83297084-7623e980-a1e1-11ea-9080-7f23255adc23.jpg)

gotchu fam hmu w/ ur paypal

**Comment by nuukedo29** [comment]
Added build script and instructions
https://github.com/nuukedo29/mifs/blob/master/doc/build.md
https://github.com/nuukedo29/mifs/blob/master/build.py
