### ISSUE TITLE
arbitrary files are broken

### ISSUE THREAD

**Issue by flumf** [nuukedo29/mifs#5]
read title retard

```
:(
OOPSIE WOOPSIE!!

OOPSIE WOOPSIE!! Uwu We make a fucky wucky!! A wittle fucko boingo! The code monkeys at our headquarters are working VEWY HAWD to fix this!

Traceback (most recent call last):
  File "mifs.py", line 270, in <module>
  File "mifs.py", line 66, in run_progress
  File "subprocess.py", line 854, in __init__
  File "subprocess.py", line 1307, in _execute_child
OSError: [WinError 740] The requested operation requires elevation
```

**Comment by mysterioushackerman** [comment]
It's been nearly a day, nya~, and this simple error still hasn't been fixed. Has the developer completely given up?

-- Hugs and Bugs, Mysterioushackerman :3

**Comment by nuukedo29** [comment]
> 
> 
> It's been nearly a day, nya~, and this simple error still hasn't been fixed. Has the developer completely given up?
> 
> -- Hugs and Bugs, Mysterioushackerman :3
> 
> Edit: @flumf , you may not be aware that the R-word is considered an ableist slur. This hateful language has been historically used to mercilessly mock autistic people, including myself and much of the GitHub community. As you are an official contributor to this project, I would like to request that you please edit it out of your post.
> 
> -- Snuggles and Kissies, Mysterioushackerman :3

i can't believe alex is pretending to be a tranny

**Comment by flumf** [comment]
cute and funny

**Comment by mysterioushackerman** [comment]
*growls* It's stiww bwoken :3 
Anybody out thewe? ;3 

-- Glomps and Smooches, Mysterioushackerman :3

**Comment by flumf** [comment]
L

**Comment by flumf** [comment]
come back grunk we miss you
